### ISSUE TITLE
Imágenes equipo

### ISSUE THREAD

**Issue by jljorro** [sismotur/WebSismotur#11]
Añadir las imágenes y los textos en equipo.

**Comment by sismotur** [comment]
Natalija: sabe que hace falta una nueva foto, la manda
Daniel: me ha dicho que le ha mandado la foto a Mario

**Comment by sismotur** [comment]
Por qué hay retraso en las fotos?
Creí que ya estaban

**Comment by sismotur** [comment]
Gracias por todo, sé que no ha sido fácil
