### ISSUE TITLE
El menú no se repliega en teléfonos móviles

### ISSUE THREAD

**Issue by felipesanti** [sismotur/WebSismotur#12]
Cuando se hace click en el teléfono móvil fuera del menú, éste no se cierra

Parece ser un problema bootstrap.
He encontrado esto en stackoverflow
http://stackoverflow.com/questions/21496304/bootstrap-collapse-component-not-closing-menu-on-clicking-away

<script>
$(document).on('click',function(){
$('.collapse').collapse('hide');
})
</script>

**Comment by sismotur** [comment]
José Luis, tomo nota de tus comentarios, lo dejamos para el final.

**Comment by sismotur** [comment]
Para amortiguar el impacto sería posible poner una flecha en la barra de menú en lugar de las rayas horizontales? 
hacia abajo si el menú está plegado y hacia arriba en caso contrario

**Comment by jljorro-smt** [comment]
Para eso es necesario tocar todo el javascript del menú. SI no es urgente lo dejamos para más adelante.

**Comment by sismotur** [comment]
Solucionado por Mario !
