### ISSUE TITLE
Bajar sangrados "Atendemos las necesidades de cada cliente"

### ISSUE THREAD

**Issue by sismotur** [sismotur/WebSismotur#13]
Disminuir el sangrado en los textos en zonas grises tipo "Atendemos las necesidades de cada cliente"

**Comment by sismotur** [comment]
El sangrado me sigue pareciendo demasiado elevado en PC bajo la primera zona gris...

**Comment by jljorro** [comment]
He disminuido el margen superior entre los objetivos y la zona gris.

**Comment by sismotur** [comment]
Done
Gracias JL
