### ISSUE TITLE
Variabilizar enlace a vídeo drontrip por idioma

### ISSUE THREAD

**Issue by sismotur** [sismotur/WebSismotur#17]
Hay que hacer que los enlaces al vídeo DronTrip en drontrip html apunten al idioma adecuado.
Ahora está hardcoded en español: https://www.youtube.com/watch?v=wS6si4eHHFY

**Comment by jljorro** [comment]
Ya esta arreglado.

**Comment by sismotur** [comment]
en sismotur.js el vídeo depende del idioma del navegador.
Pero el programa no gestiona un cambio de idioma por parte del usuario, p.ej. si cambio del español (idioma de mi navegador) al inglés el vídeo me sigue saliendo en español.

Creo que hay que crear una variable interna en la web que mantenga el lenguaje deseado durante la vida del programa. Al momento de cargar la página se elige el idioma del navegador, luego se sustituye por el que el usuario solicite

**Comment by jljorro** [comment]
Ya esta arreglado. Ahora se lee la variable lang de la cookie si existe, en caso contrario, se lee el idioma del navegador.

**Comment by sismotur** [comment]
buena corrección
