### ISSUE TITLE
Sangrado en zona tecnología

### ISSUE THREAD

**Issue by sismotur** [sismotur/WebSismotur#20]
Ej. en Beacons, el texto descriptivo se "come" el botón al ver la página en un teléfono móvil

**Comment by jljorro** [comment]
Ya esta arreglado.

**Comment by sismotur** [comment]
Siento ser tan pesado con este tema.
Ahora el problema es que en teléfonos móviles el sangrado del QR es tan excesivo que al hacer scroll hacia abajo queda un espacio blanco importante entre el logo del QR y el botón.
Hay alguna forma de hacer que?
- el sangrado sea fijo si estamos en un PC o tableta
- el sangrado sea variable (el botón va justo tras el texto) si estamos en un móvil

Si lo veis complicado puedo añadir en primera instancia más texto para llenar el hueco

**Comment by jljorro** [comment]
He modificado la altura del párrafo de QR para móviles. Ahora es más pequeño.

**Comment by sismotur** [comment]
buena corrección 
no me acaba de convencer del todo las distancias entre elementos (título / menú  / botón ) pero para esta versión está ok
