### ISSUE TITLE
Pesos de las imagenes

### ISSUE THREAD

**Issue by jljorro** [sismotur/WebSismotur#3]
Reducir el peso de las imágenes porque tardan mucho en bajarse. Ponerles un peso de aproximadamente 300KB.

**Comment by sismotur** [comment]
Sobre todo en la foto del dron situada en drontrip.html

**Comment by sismotur** [comment]
Lo podemos cerrar?
Insisto, poned comentarios confirmando que las cosas se hacen, es necesario para poder cerrar las cosas con conocimiento de causa.

**Comment by jljorro** [comment]
Ya se han reducido
