### ISSUE TITLE
Flecha en Cabecera.

### ISSUE THREAD

**Issue by jljorro** [sismotur/WebSismotur#5]
Añadir una flecha que señale hacia abajo en la cabecera para que la gente sepa que tiene que hacer scroll hacia abajo.

**Comment by sismotur** [comment]
La flecha no funciona en teléfono móvil. 
Por otra parte no añade mucha funcionalidad.
Sería posible dejarla en PC / tableta y quitarla en móvil?

**Comment by jljorro-smt** [comment]
He eliminado la flecha en moviles.

**Comment by sismotur** [comment]
ok perfecto
