### ISSUE TITLE
Terminar Página de DronTrip

### ISSUE THREAD

**Issue by jljorro** [sismotur/WebSismotur#6]
Terminar la página de DronTrip:
- Añadir título de DronTrip.
- Poner texto si fuera necesario.
- Mejorar contraste fotografía, texto y botón para que se vea bien el contenido.

**Comment by jljorro** [comment]
Versión de escritorio terminada, hay que estudiar si hay que mejorar los contrastes para la versión movil.

**Comment by sismotur** [comment]
Gracias
Yo la veo muy bien para una v1 de la web.
Ya le daremos una vuelta después de Fitur.
